tensorqtl_path: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/tensorqtl/tensorqtl'
misc_tools_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools/pyutil'
wrapper_script: 'run_trans_qtl.py'
genotype: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/subset_genotypes/IDP_HM3_finalPheno.chr{chr_num}.bed'
covariate: 
  table: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/phenotypes/imagexcan_covariate_round_1.parquet'
  metainfo: 'covar.yaml'
  indiv_col: 'eid'
phenotype: 
  table: '/gpfs/data/im-lab/nas40t2/yanyul/ukb_idp/regress_out_idp_pcs/2020-05-18_final-phenotypes.cleaned_up_T1.parquet'
  indiv_col: 'individual'
map_trans_yaml: 'map_trans.yaml'
